Token: 7315536718:AAHUH9yNmvDhc8kgHhFTpLRmbdZRNH7wIvY
BotModules:
  ReactionCounter:
    In:
      Type: http
      Host: localhost
      Port: 6001
      Endpoint: /getUpdates
    AllowedUpdates:
      Group,Supergroup:
        - message
        - my_chat_member
        - chat_member
        - message_reaction
        - message_reaction_count
    AllowedChats:
      Group,SuperGroup:
        - -1002490626579
        - -1002257766850

  BeerEventManager:
    In:
      Type: http
      Host: localhost
      Port: 6002
      Endpoint: /processUpdate
    AllowedUpdates:
      Channel,Group,Supergroup:
        - message
        - my_chat_member
        - chat_member
        - channel_post
      Poll:
        - poll
        - poll_answer
    AllowedChats:
      Group,Channel,SuperGroup:
        - -1002490626579
        - -1002257766850
      Poll:
        - all