version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Beer4Helper.ReactionCounter/Dockerfile
    container_name: telegram_reaction_bot
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgreSQL=Host=postgres;Port=5432;Database=reaction_bot;Username=postgres;Password=postgres
    restart: always

  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_DB: reaction_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
