# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  event-module-test:
    build:
      context: "C:\\_git\\Beer4Helper"
      dockerfile: "Beer4Helper.BeerEventManager/test.Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/Beer4Helper.BeerEventManager.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "beer4helper.beereventmanager:dev"
    ports: []
    volumes:
    - "C:\\_git\\Beer4Helper\\Beer4Helper.BeerEventManager:/app:rw"
    - "C:\\_git\\Beer4Helper:/src:rw"
    - "C:\\Users\\vasilev\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app"
